config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :questionnaires, param: :slug, only: %i[index show] do
    member do
      get ':uid/steps/:step_position', to: 'steps#show_questions'
      post ':uid/steps/:step_position', to: 'steps#save_answers'
      get 'completed'
    end
  end
  
  root 'questionnaires#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :result
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/possible_answer.rb
class PossibleAnswer < ApplicationRecord
  belongs_to :question
  
  validates :value, :position, presence: true
  validates_uniqueness_of :position, scope: :question_id
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :step
  has_many :possible_answers, dependent: :destroy
  has_many :answers, dependent: :destroy
  
  validates :value, :answer_type, :position, presence: true
  validates_uniqueness_of :position, scope: :step_id
  
  enum answer_type: %w[STRING INTEGER RADIO CHECKBOXES]
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :steps, dependent: :destroy
  has_many :results, dependent: :destroy
  
  validates :name, :slug, presence: true
  validates :slug, uniqueness: { case_sensitive: false }
  
  before_save { |record| record.slug = record.slug.gsub(/[[:space:]]/, '').downcase }
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  
  validates :uid, presence: true
  validates_uniqueness_of :uid, scope: :questionnaire_id
end

app/models/result_item.rb
class ResultItem < ApplicationRecord
  belongs_to :result
  belongs_to :question
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :questionnaire
  has_many :questions, dependent: :destroy
  
  validates :position, presence: true
  validates_uniqueness_of :position, scope: :questionnaire_id
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_questionnaire

  private
  
    def set_questionnaire
      @questionnaire = Questionnaire.find_by(slug: params[:slug])
      redirect_to 'questionnaires#index' unless @questionnaire
    end
    
    def redirect_to_first_step
      uid = "uid#{Time.now.to_i.to_s}"
      redirect_to "/questionnaires/#{@questionnaire.slug}/#{uid}/steps/1" 
    end
end

app/controllers/questionnaires_controller.rb
# frozen_string_literal: true

class QuestionnairesController < ApplicationController
  skip_before_action :set_questionnaire, only: :index

  def index
    @questionnaires = Questionnaire.all  
  end
  
  def show
    redirect_to_first_step
  end
  
  def completed; end
end

app/controllers/steps_controller.rb
# frozen_string_literal: true

class StepsController < ApplicationController
  def show_questions
    @step = @questionnaire.steps.find_by(position: params[:step_position])
    return redirect_to_first_step unless @step
    
    @result = @questionnaire.results&.find_by(uid: params[:uid])
  end

  def save_answers
    @validation_errors = {}
    params[:questions].each do |question_id, value|
      @question= Question.find(question_id)
      
      value.shift if @question.answer_type == 'CHECKBOXES'
      value.strip! if @question.answer_type == 'STRING'
      
      @validation_errors[question_id] = validate_value(@question, value)
      if @validation_errors[question_id].nil?
        result = Result.find_or_create_by(uid: params[:uid], questionnaire_id: @questionnaire.id)
        answer = Answer.find_or_create_by(result_id: result.id, question_id: question_id)
        answer.update(value: value) unless answer.value == value
      end
    end
    
    step_position = params[:step_position].to_i
    
    if @validation_errors.values.any?
      @step = @questionnaire.steps.find_by(position: params[:step_position])
      @result = @questionnaire.results&.find_by(uid: params[:uid])
      return render :show_questions 
    end
    
    return redirect_to completed_questionnaire_path(@questionnaire.slug) if last_step?(step_position)
    
    redirect_to "/questionnaires/#{ @questionnaire.slug }/#{params[:uid]}/steps/#{ step_position + 1 }"
  end
  
  private
  
  def last_step?(step_position)
    @questionnaire.steps.order(:position).last.position == step_position
  end
  
  def validate_value(question, value)
    if question.answer_required
      return {presence: false} unless value.present?
    end  
    
    if question.answer_type == 'STRING' && question.min_value && question.max_value && 
                                           !value.length.between?(question.min_value, question.max_value) 
      return {length: false} 
    end
    
    if question.answer_type == 'INTEGER' && question.min_value && question.max_value && 
                                            !value.to_i.between?(question.min_value, question.max_value) 
      return {span: false}
    end
    nil
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
  def answer_value(result, question_id)
    result&.answers&.find_by(question_id: question_id)&.value
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bacano-Questionnaires</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-purple font-sans antialiased">
    <div class="my-6 px-4">
      <div class="mx-auto max-w-xl">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questionnaires/completed.html.erb
<div class="text-center">
  <h1 class="text-white text-3xl"><%= @questionnaire.name %></h1>
</div>

<div class="grid grid-cols-8 gap-4 my-12 bg-white rounded shadow-lg pt-10 pb-8">
  <div class="col-span-6 col-start-2">
    <p>Thank you!</p>
    <p>You have fulfilled the Questionnaire</p>
  </div>
</div>

<div class="mb-6 text-center">
  <%= link_to "Back to Questionnaire Index", root_path, class: 'text-white' %>
</div>

app/views/questionnaires/index.html.erb
<div class="text-center">
  <h1 class="text-white text-3xl">Questionnaires</h1>
</div>

<div class="grid grid-cols-8 gap-4 my-12 bg-white rounded shadow-lg pt-10 pb-8">
  <div class="col-span-6 col-start-2">
    <ul>
      <% @questionnaires.each do |questionnaire| %>
        <li><%= link_to questionnaire.name, questionnaire_path(questionnaire.slug) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/steps/_question.html.erb
<div class="mb-6">
  <label for="company_name" class="string optional block mb-1 font-semibold w-full text-sm">
    <%= question.value %>
  </label>

  <%= render "steps/answers_by_type/#{question.answer_type.downcase}", 
             question: question %>
</div>

app/views/steps/answers_by_type/_checkboxes.html.erb
<fieldset class="block">
  <div class="mb-3 text-sm text-gray-400">
    <%= question.answer_required ? 'Select one or more options' : 'You can select a few options' %>  
  </div>
  <%= collection_check_boxes :questions, "#{question.id}", question.possible_answers.order(:position), :id, :value,
                             { checked: answer_value(@result, question.id) } do |b| %>
    <span class="checkbox">
      <%= b.label(class: 'w-full inline-flex items-center mb-2 cursor-pointer text-sm text-gray-700') do
            b.check_box(class: 'form-checkbox mr-2') + b.text
          end %>
    </span>
  <% end %>
</fieldset>

<% if @validation_errors && @validation_errors[question.id.to_s] %>
  <div class="text-sm text-red-400">You should choose at least one option</div>
<% end %>

app/views/steps/answers_by_type/_integer.html.erb
<div class="block">
  <%= number_field_tag "questions[#{question.id}]", answer_value(@result, question.id)&.to_i,
                     class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
</div>

<% if @validation_errors && @validation_errors[question.id.to_s] %>
  <% if @validation_errors[question.id.to_s].keys.first == :presence %>
    <span class="block text-sm text-red-400">Value cannot be blank</span>
  <% else %>
    <span class="block text-sm text-red-400">
      Value must be between <%= question.min_value %> and <%= question.max_value %>
    </span>
  <% end %>
<% end %>

app/views/steps/answers_by_type/_radio.html.erb
<fieldset class="radio_buttons">
  <%= collection_radio_buttons :questions, "#{question.id}", question.possible_answers.order(:position), :id, :value,
                               { checked: answer_value(@result, question.id) } do |b| %>
    <span class="radio">
      <%= b.label(class: 'inline-flex items-center mr-4 mb-2 cursor-pointer text-sm text-gray-700') do
          b.radio_button(class: 'form-radio mr-2 focus:outline-none is-invalid 
                                 cursor-pointer text-blue-500 transition duration-150 
                                 ease-in-out') + b.text
        end %>
    </span>
  <% end %>
</fieldset>

<% if @validation_errors && @validation_errors[question.id.to_s] %>
  <div class="text-sm text-red-400">You should choose one option</div>
<% end %>

app/views/steps/answers_by_type/_string.html.erb
<div class="block">
  <%= text_field_tag "questions[#{question.id}]", answer_value(@result, question.id),
                     class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight 
                             focus:outline-none focus:shadow-outline' %>
</div>

<% if @validation_errors && @validation_errors[question.id.to_s] %>
  <% if @validation_errors[question.id.to_s].keys.first == :presence %>
    <span class="block text-sm text-red-400">Value cannot be blank</span>
  <% else %>
    <span class="block text-sm text-red-400">
      Length must be between <%= question.min_value %> and <%= question.max_value %>
    </span>
  <% end %>
<% end %>

app/views/steps/show_questions.html.erb
<div class="text-center">
  <h1 class="text-white text-3xl"><%= @questionnaire.name %></h1>
</div>

<div class="grid grid-cols-8 gap-4 my-12 bg-white rounded shadow-lg pt-10 pb-8">
  <div class="col-span-6 col-start-2">
    <%= form_with url: "/questionnaires/#{ @questionnaire.slug }/#{params[:uid]}/steps/#{ params[:step_position] }", 
                  local: true, class: 'simple_form' do |f| %>
      <%= render partial: 'question', collection: @step.questions.order(:position) %>
      <div class="<%= params[:step_position] == '1' ? 'mt-12 text-center' : 'flex justify-between items-center mt-12' %>">
        <% if params[:step_position] != '1' %>
          <span class="inline-flex rounded-full shadow">
            <%= link_to "Back", 
                "/questionnaires/#{ @questionnaire.slug }/#{ params[:uid] }/steps/#{ params[:step_position].to_i - 1 }",
                class: 'cursor-pointer inline-flex items-center px-4 py-2 border border-transparent text-sm 
                        leading-5 font-medium rounded-full text-gray-700 bg-gray-100 hover:bg-gray-200 
                        focus:outline-none focus:border-pink focus:shadow-outline-pink active:bg-pink 
                        transition ease-in-out duration-150' %>
          </span>  
        <% end %>
        <span class="inline-flex rounded-full shadow">
          <%= f.submit 'Continue', class: 'cursor-pointer inline-flex items-center px-4 py-2 border border-transparent 
                                           text-sm leading-5 font-medium rounded-full text-white bg-pink 
                                           focus:outline-none focus:border-pink focus:shadow-outline-pink' %>
        </span>
      </div>
    <% end %>
  </div>
</div>

<div class="mb-6 text-center">
  <%= link_to "Back to Questionnaire Index", root_path, class: 'text-white' %>
</div>